spring.application.name=hocho

# MS SQL Server Config
spring.datasource.url=jdbc:sqlserver://hocho.database.windows.net:1433;\
  database=hocho-db;\
  encrypt=true;trustServerCertificate=true;\
  hostNameInCertificate=hocho.database.windows.net;
spring.datasource.username=hocho
spring.datasource.password=Thinh1672005@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# default default
spring.security.user.name=admin
spring.security.user.password=123

server.address=0.0.0.0

# Actuator config
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

spring.web.resources.static-locations=classpath:/static/,file:/D:/code/intellij_Ultimate/res/static/

# Cho phép nh?n file l?n h?n ?? backend có th? scale
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


spring.security.oauth2.client.registration.google.client-id=9680843011-fop6lbqihr05a4eldukjqhadragv9v0n.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
# spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid,email,profile

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/userinfo/v2/me
spring.security.oauth2.client.provider.google.user-name-attribute=email

# Email config

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=de180352vubinhminh@gmail.com
spring.mail.password=l p z c k w s k s r c d b k r x
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend URL

frontend.url=http://localhost:3000


# payment
#Minh
#PAYOS_CLIENT_ID=d3716d13-ce91-4554-bcf5-f1207e841650
#PAYOS_API_KEY=6cbb7553-6c33-4021-b046-9607ef0025ab
#PAYOS_CHECKSUM_KEY=683efd0ccd9ced234b0be0ed3073cfe01290d7a3e4cbea64c0cd8b62e9ae6591

#Phuoc
PAYOS_CLIENT_ID=6c9bc89d-8cb6-4370-82e5-d293b458ad23
PAYOS_API_KEY=0b85c722-825f-4ff8-a194-8a1cc9a52ad1
PAYOS_CHECKSUM_KEY=3a63bb7fa59884dd7ae0047afd728e2f4c7fd229d680d2848a852a1a224586f3

app.base-url=http://localhost:3000

# Payment Configuration
payment.return-url=${app.base-url}/hocho/payment/return
payment.cancel-url=${app.base-url}/hocho/payment/cancel
payment.webhook-url=${app.base-url}/hocho/payment/webhook


# logging.level.org.springframework.security=DEBUG
# logging.level.d10_rt01.hocho.security=DEBUG
# logging.level.org.springframework.web=DEBUG
# logging.level.d10_rt01.hocho=DEBUG
# logging.level.root=INFO
